// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.axisbank.netbanking.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Account_SOAPBuilder implements SOAPInstanceBuilder {
    private com.axisbank.netbanking.service.Account _instance;
    private java.lang.String accountNo;
    private java.lang.String accountHolderName;
    private java.lang.String ifscCode;
    private static final int myACCOUNTNO_INDEX = 0;
    private static final int myACCOUNTHOLDERNAME_INDEX = 1;
    private static final int myIFSCCODE_INDEX = 2;
    
    public Account_SOAPBuilder() {
    }
    
    public void setAccountNo(java.lang.String accountNo) {
        this.accountNo = accountNo;
    }
    
    public void setAccountHolderName(java.lang.String accountHolderName) {
        this.accountHolderName = accountHolderName;
    }
    
    public void setIfscCode(java.lang.String ifscCode) {
        this.ifscCode = ifscCode;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myACCOUNTNO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myACCOUNTHOLDERNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myIFSCCODE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myACCOUNTNO_INDEX:
                    _instance.setAccountNo((java.lang.String)memberValue);
                    break;
                case myACCOUNTHOLDERNAME_INDEX:
                    _instance.setAccountHolderName((java.lang.String)memberValue);
                    break;
                case myIFSCCODE_INDEX:
                    _instance.setIfscCode((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.axisbank.netbanking.service.Account)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
