// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.axisbank.netbanking.service;


public class Account {
    protected java.lang.String accountNo;
    protected java.lang.String accountHolderName;
    protected java.lang.String ifscCode;
    
    public Account() {
    }
    
    public Account(java.lang.String accountNo, java.lang.String accountHolderName, java.lang.String ifscCode) {
        this.accountNo = accountNo;
        this.accountHolderName = accountHolderName;
        this.ifscCode = ifscCode;
    }
    
    public java.lang.String getAccountNo() {
        return accountNo;
    }
    
    public void setAccountNo(java.lang.String accountNo) {
        this.accountNo = accountNo;
    }
    
    public java.lang.String getAccountHolderName() {
        return accountHolderName;
    }
    
    public void setAccountHolderName(java.lang.String accountHolderName) {
        this.accountHolderName = accountHolderName;
    }
    
    public java.lang.String getIfscCode() {
        return ifscCode;
    }
    
    public void setIfscCode(java.lang.String ifscCode) {
        this.ifscCode = ifscCode;
    }
}
