// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.axisbank.netbanking.service;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class FundsTransfer_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public FundsTransfer_Tie() throws Exception {
        super(new com.axisbank.netbanking.service.RbiGatewayService_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: neft
     */
    private void invoke_neft(StreamingHandlerState state) throws Exception {
        
        com.axisbank.netbanking.service.FundsTransfer_neft_RequestStruct myFundsTransfer_neft_RequestStruct = null;
        Object myFundsTransfer_neft_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myFundsTransfer_neft_RequestStructObj instanceof SOAPDeserializationState) {
            myFundsTransfer_neft_RequestStruct = (com.axisbank.netbanking.service.FundsTransfer_neft_RequestStruct)((SOAPDeserializationState)myFundsTransfer_neft_RequestStructObj).getInstance();
        } else {
            myFundsTransfer_neft_RequestStruct = (com.axisbank.netbanking.service.FundsTransfer_neft_RequestStruct)myFundsTransfer_neft_RequestStructObj;
        }
        
        try {
            com.axisbank.netbanking.service.Receipt result = 
                ((com.axisbank.netbanking.service.FundsTransfer) getTarget()).neft(myFundsTransfer_neft_RequestStruct.getFromAc(), myFundsTransfer_neft_RequestStruct.getToAc(), myFundsTransfer_neft_RequestStruct.getNeftDetails());
            com.axisbank.netbanking.service.FundsTransfer_neft_ResponseStruct myFundsTransfer_neft_ResponseStruct =
                new com.axisbank.netbanking.service.FundsTransfer_neft_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myFundsTransfer_neft_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_neft_neftResponse_QNAME);
            bodyBlock.setValue(myFundsTransfer_neft_ResponseStruct);
            bodyBlock.setSerializer(ns1_myFundsTransfer_neft_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_neft_neft_QNAME)) {
            state.getRequest().setOperationCode(neft_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case neft_OPCODE:
                deserialize_neft(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the neft operation.
     */
    private void deserialize_neft(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myFundsTransfer_neft_RequestStructObj =
            ns1_myFundsTransfer_neft_RequestStruct_SOAPSerializer.deserialize(ns1_neft_neft_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_neft_neft_QNAME);
        bodyBlock.setValue(myFundsTransfer_neft_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case neft_OPCODE:
                invoke_neft(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_neft_neft_QNAME)) {
            return neft_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case neft_OPCODE:
                {
                    Class[] carray = { com.axisbank.netbanking.service.Account.class,com.axisbank.netbanking.service.Account.class,com.axisbank.netbanking.service.NeftDetails.class };
                    theMethod = (com.axisbank.netbanking.service.FundsTransfer.class).getMethod("neft", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[1];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 1 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myFundsTransfer_neft_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.axisbank.netbanking.service.FundsTransfer_neft_RequestStruct.class, ns1_neft_TYPE_QNAME);
        ns1_myFundsTransfer_neft_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.axisbank.netbanking.service.FundsTransfer_neft_ResponseStruct.class, ns1_neftResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://axisbank.com/netbanking/service", "fundsTransferSOAPPort");
    private static final int neft_OPCODE = 0;
    private static final javax.xml.namespace.QName ns1_neft_neft_QNAME = new QName("http://axisbank.com/netbanking/service", "neft");
    private static final javax.xml.namespace.QName ns1_neft_TYPE_QNAME = new QName("http://axisbank.com/netbanking/service", "neft");
    private CombinedSerializer ns1_myFundsTransfer_neft_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_neft_neftResponse_QNAME = new QName("http://axisbank.com/netbanking/service", "neftResponse");
    private static final javax.xml.namespace.QName ns1_neftResponse_TYPE_QNAME = new QName("http://axisbank.com/netbanking/service", "neftResponse");
    private CombinedSerializer ns1_myFundsTransfer_neft_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://axisbank.com/netbanking/service",
                                            "ns1", "http://axisbank.com/netbanking/types"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
