// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.axisbank.netbanking.service;


public class FundsTransfer_neft_ResponseStruct {
    protected com.axisbank.netbanking.service.Receipt result;
    
    public FundsTransfer_neft_ResponseStruct() {
    }
    
    public FundsTransfer_neft_ResponseStruct(com.axisbank.netbanking.service.Receipt result) {
        this.result = result;
    }
    
    public com.axisbank.netbanking.service.Receipt getResult() {
        return result;
    }
    
    public void setResult(com.axisbank.netbanking.service.Receipt result) {
        this.result = result;
    }
}
