// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.axisbank.netbanking.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class NeftDetails_SOAPBuilder implements SOAPInstanceBuilder {
    private com.axisbank.netbanking.service.NeftDetails _instance;
    private float amount;
    private java.lang.String comments;
    private static final int myAMOUNT_INDEX = 0;
    private static final int myCOMMENTS_INDEX = 1;
    
    public NeftDetails_SOAPBuilder() {
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    
    public void setComments(java.lang.String comments) {
        this.comments = comments;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myCOMMENTS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myCOMMENTS_INDEX:
                    _instance.setComments((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.axisbank.netbanking.service.NeftDetails)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
