// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.axisbank.netbanking.service;


public class NeftDetails {
    protected float amount;
    protected java.lang.String comments;
    
    public NeftDetails() {
    }
    
    public NeftDetails(float amount, java.lang.String comments) {
        this.amount = amount;
        this.comments = comments;
    }
    
    public float getAmount() {
        return amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    
    public java.lang.String getComments() {
        return comments;
    }
    
    public void setComments(java.lang.String comments) {
        this.comments = comments;
    }
}
