// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.icicibank.netbanking.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class FundsTransfer_neft_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_fromAc_QNAME = new QName("", "fromAc");
    private static final javax.xml.namespace.QName ns2_account_TYPE_QNAME = new QName("http://axisbank.com/netbanking/types", "account");
    private CombinedSerializer ns2_myAccount_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_toAc_QNAME = new QName("", "toAc");
    private static final javax.xml.namespace.QName ns1_neftDetails_QNAME = new QName("", "neftDetails");
    private static final javax.xml.namespace.QName ns2_neftDetails_TYPE_QNAME = new QName("http://axisbank.com/netbanking/types", "neftDetails");
    private CombinedSerializer ns2_myNeftDetails_SOAPSerializer;
    private static final int myFROMAC_INDEX = 0;
    private static final int myTOAC_INDEX = 1;
    private static final int myNEFTDETAILS_INDEX = 2;
    
    public FundsTransfer_neft_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myAccount_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.icicibank.netbanking.service.Account.class, ns2_account_TYPE_QNAME);
        ns2_myNeftDetails_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.icicibank.netbanking.service.NeftDetails.class, ns2_neftDetails_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct instance = new com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct();
        com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<3; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_fromAc_QNAME)) {
                member = ns2_myAccount_SOAPSerializer.deserialize(ns1_fromAc_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myFROMAC_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setFromAc((com.icicibank.netbanking.service.Account)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_toAc_QNAME)) {
                member = ns2_myAccount_SOAPSerializer.deserialize(ns1_toAc_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTOAC_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setToAc((com.icicibank.netbanking.service.Account)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_neftDetails_QNAME)) {
                member = ns2_myNeftDetails_SOAPSerializer.deserialize(ns1_neftDetails_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myNEFTDETAILS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setNeftDetails((com.icicibank.netbanking.service.NeftDetails)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_neftDetails_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct instance = (com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct instance = (com.icicibank.netbanking.service.FundsTransfer_neft_RequestStruct)obj;
        
        ns2_myAccount_SOAPSerializer.serialize(instance.getFromAc(), ns1_fromAc_QNAME, null, writer, context);
        ns2_myAccount_SOAPSerializer.serialize(instance.getToAc(), ns1_toAc_QNAME, null, writer, context);
        ns2_myNeftDetails_SOAPSerializer.serialize(instance.getNeftDetails(), ns1_neftDetails_QNAME, null, writer, context);
    }
}
