// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.icicibank.netbanking.service;


public class FundsTransfer_neft_RequestStruct {
    protected com.icicibank.netbanking.service.Account fromAc;
    protected com.icicibank.netbanking.service.Account toAc;
    protected com.icicibank.netbanking.service.NeftDetails neftDetails;
    
    public FundsTransfer_neft_RequestStruct() {
    }
    
    public FundsTransfer_neft_RequestStruct(com.icicibank.netbanking.service.Account fromAc, com.icicibank.netbanking.service.Account toAc, com.icicibank.netbanking.service.NeftDetails neftDetails) {
        this.fromAc = fromAc;
        this.toAc = toAc;
        this.neftDetails = neftDetails;
    }
    
    public com.icicibank.netbanking.service.Account getFromAc() {
        return fromAc;
    }
    
    public void setFromAc(com.icicibank.netbanking.service.Account fromAc) {
        this.fromAc = fromAc;
    }
    
    public com.icicibank.netbanking.service.Account getToAc() {
        return toAc;
    }
    
    public void setToAc(com.icicibank.netbanking.service.Account toAc) {
        this.toAc = toAc;
    }
    
    public com.icicibank.netbanking.service.NeftDetails getNeftDetails() {
        return neftDetails;
    }
    
    public void setNeftDetails(com.icicibank.netbanking.service.NeftDetails neftDetails) {
        this.neftDetails = neftDetails;
    }
}
