// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.icicibank.netbanking.service;

public interface FundsTransfer extends java.rmi.Remote {
    public com.icicibank.netbanking.service.Receipt neft(com.icicibank.netbanking.service.Account fromAc, com.icicibank.netbanking.service.Account toAc, com.icicibank.netbanking.service.NeftDetails neftDetails) throws 
         java.rmi.RemoteException;
}
