// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.icicibank.netbanking.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class RbiGatewayService_Impl extends com.sun.xml.rpc.client.BasicService implements RbiGatewayService {
    private static final QName serviceName = new QName("http://axisbank.com/netbanking/service", "rbiGatewayService");
    private static final QName ns1_fundsTransferSOAPPort_QNAME = new QName("http://axisbank.com/netbanking/service", "fundsTransferSOAPPort");
    private static final Class fundsTransfer_PortClass = com.icicibank.netbanking.service.FundsTransfer.class;
    
    public RbiGatewayService_Impl() {
        super(serviceName, new QName[] {
                        ns1_fundsTransferSOAPPort_QNAME
                    },
            new com.icicibank.netbanking.service.RbiGatewayService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_fundsTransferSOAPPort_QNAME) &&
                serviceDefInterface.equals(fundsTransfer_PortClass)) {
                return getFundsTransferSOAPPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(fundsTransfer_PortClass)) {
                return getFundsTransferSOAPPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public com.icicibank.netbanking.service.FundsTransfer getFundsTransferSOAPPort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_fundsTransferSOAPPort_QNAME));
        handlerChain.setRoles(roles);
        com.icicibank.netbanking.service.FundsTransfer_Stub stub = new com.icicibank.netbanking.service.FundsTransfer_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
