// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.icicibank.netbanking.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Receipt_SOAPBuilder implements SOAPInstanceBuilder {
    private com.icicibank.netbanking.service.Receipt _instance;
    private java.lang.String transactionNo;
    private java.lang.String status;
    private static final int myTRANSACTIONNO_INDEX = 0;
    private static final int mySTATUS_INDEX = 1;
    
    public Receipt_SOAPBuilder() {
    }
    
    public void setTransactionNo(java.lang.String transactionNo) {
        this.transactionNo = transactionNo;
    }
    
    public void setStatus(java.lang.String status) {
        this.status = status;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myTRANSACTIONNO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTATUS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myTRANSACTIONNO_INDEX:
                    _instance.setTransactionNo((java.lang.String)memberValue);
                    break;
                case mySTATUS_INDEX:
                    _instance.setStatus((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.icicibank.netbanking.service.Receipt)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
