
package in.freerecharge.mobile.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import in.freerecharge.mobile.services.MobileManager;
import in.freerecharge.mobile.types.PaymentMethod;
import in.freerecharge.mobile.types.Receipt;
import in.freerecharge.mobile.types.Subscriber;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MobileManager", targetNamespace = "http://freerecharge.in/mobile/services", wsdlLocation = "http://localhost:8080/FreeRecharge/freerecharge?wsdl")
public interface MobileManager {


    /**
     * 
     * @param paymentMethod
     * @param subscriber
     * @return
     *     returns in.freerecharge.mobile.types.Receipt
     */
    @WebMethod(action = "http://freerecharge.in/mobile/services/recharge")
    @WebResult(name = "receipt", targetNamespace = "http://freerecharge.in/mobile/types")
    @RequestWrapper(localName = "recharge", targetNamespace = "http://freerecharge.in/mobile/types", className = "in.freerecharge.mobile.types.Recharge")
    @ResponseWrapper(localName = "rechargeResponse", targetNamespace = "http://freerecharge.in/mobile/types", className = "in.freerecharge.mobile.types.RechargeResponse")
    public Receipt recharge(
        @WebParam(name = "subscriber", targetNamespace = "http://freerecharge.in/mobile/types")
        Subscriber subscriber,
        @WebParam(name = "paymentMethod", targetNamespace = "http://freerecharge.in/mobile/types")
        PaymentMethod paymentMethod);

}
