package in.freerecharge.mobile.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import in.freerecharge.mobile.services.MobileManager;
import in.freerecharge.mobile.services.MobileManagerService;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0-b26-ea3 Generated
 * source version: 2.0
 * 
 */
@WebServiceClient(name = "MobileManagerService", targetNamespace = "http://services.mobile.freerecharge.in/", wsdlLocation = "http://localhost:8080/FreeRecharge/freerecharge?wsdl")
public class MobileManagerService extends Service {

	private final static URL WSDL_LOCATION;
	private final static QName MOBILEMANAGERSERVICE = new QName(
			"http://services.mobile.freerecharge.in/", "MobileManagerService");
	private final static QName MOBILEMANAGERSOAPPORT = new QName(
			"http://services.mobile.freerecharge.in/", "MobileManagerSOAPPort");

	static {
		URL url = null;
		try {
			url = new URL(
					"http://localhost:8080/FreeRecharge/freerecharge?wsdl");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		WSDL_LOCATION = url;
	}

	public MobileManagerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MobileManagerService(String endpointLocation)
			throws MalformedURLException {
		super(new URL(endpointLocation + "?wsdl"), MOBILEMANAGERSERVICE);
	}

	public MobileManagerService() {
		super(WSDL_LOCATION, MOBILEMANAGERSERVICE);
	}

	/**
	 * 
	 * @return returns MobileManager
	 */
	@WebEndpoint(name = "MobileManagerSOAPPort")
	public MobileManager getMobileManagerSOAPPort() {
		return (MobileManager) super.getPort(MOBILEMANAGERSOAPPORT,
				MobileManager.class);
	}

}
