package com.oyo.reservation.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2018-07-24T10:29:36.942+05:30
 * Generated source version: 2.6.9
 * 
 */
@WebService(targetNamespace = "http://oyo.com/reservation/services", name = "oyo")
@XmlSeeAlso({com.oyo.reservation.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Oyo {

    @WebMethod(action = "http://oyo.com/reservation/services/bookRoom")
    @WebResult(name = "reservation", targetNamespace = "http://oyo.com/reservation/types", partName = "out")
    public com.oyo.reservation.types.Reservation bookRoom(
        @WebParam(partName = "in", name = "checkin", targetNamespace = "http://oyo.com/reservation/types")
        com.oyo.reservation.types.Checkin in
    );
}
