package com.oyo.reservation.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2018-07-23T10:58:28.595+05:30
 * Generated source version: 2.6.9
 * 
 */
@WebServiceClient(name = "oyo", 
                  wsdlLocation = "file:WebContent/WEB-INF/oyo.wsdl",
                  targetNamespace = "http://oyo.com/reservation/services") 
public class Oyo_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://oyo.com/reservation/services", "oyo");
    public final static QName OyoSOAPPort = new QName("http://oyo.com/reservation/services", "oyoSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:WebContent/WEB-INF/oyo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Oyo_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:WebContent/WEB-INF/oyo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Oyo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Oyo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Oyo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Oyo
     */
    @WebEndpoint(name = "oyoSOAPPort")
    public Oyo getOyoSOAPPort() {
        return super.getPort(OyoSOAPPort, Oyo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Oyo
     */
    @WebEndpoint(name = "oyoSOAPPort")
    public Oyo getOyoSOAPPort(WebServiceFeature... features) {
        return super.getPort(OyoSOAPPort, Oyo.class, features);
    }

}
