
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oyo.reservation.services;

import java.util.UUID;
import java.util.logging.Logger;

import com.oyo.reservation.types.Reservation;

/**
 * This class was generated by Apache CXF 2.6.9 2018-07-23T10:58:28.564+05:30
 * Generated source version: 2.6.9
 * 
 */

@javax.jws.WebService(serviceName = "oyo", portName = "oyoSOAPPort", targetNamespace = "http://oyo.com/reservation/services", wsdlLocation = "WEB-INF/oyo.wsdl", endpointInterface = "com.oyo.reservation.services.Oyo")

public class OyoImpl implements Oyo {
	private static final Logger LOG = Logger.getLogger(OyoImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.oyo.reservation.services.Oyo#bookRoom(com.oyo.reservation.types.Checkin
	 * in )*
	 */
	public com.oyo.reservation.types.Reservation bookRoom(com.oyo.reservation.types.Checkin in) {
		LOG.info("Executing operation bookRoom");
		System.out.println(in);
		Reservation reservation = new Reservation();
		reservation.setBookingNo(UUID.randomUUID().toString());
		reservation.setStatus(in.getRoomType() + " has been reserved");
		return reservation;
	}

}
